LOCAL_PATH := $(call my-dir)

ENGINE_PATH := $(LOCAL_PATH)/../../../../../..
ENGINE_PATH_FROM_SRC := ../../../../../..

$(call import-add-path,$(ENGINE_PATH))

#Android与系统交互部分
include $(CLEAR_VARS)
LOCAL_MODULE    := GXAndroid
LOCAL_C_INCLUDES:= $(ENGINE_PATH)/src
LOCAL_CFLAGS 	+= -DGX_OS_ANDROID -Wno-multichar 
LOCAL_CPPFLAGS	+= -DGX_OS_ANDROID -fno-rtti
LOCAL_SRC_FILES := \
 $(ENGINE_PATH_FROM_SRC)/src/GJNI.cpp \
 $(ENGINE_PATH_FROM_SRC)/src/GAndroid.cpp \
 $(ENGINE_PATH_FROM_SRC)/src/GAndroidC.cpp \
 $(ENGINE_PATH_FROM_SRC)/src/GAndroidJ.cpp \

include $(BUILD_STATIC_LIBRARY)

include $(CLEAR_VARS)

LOCAL_MODULE    := GX
LOCAL_C_INCLUDES:= $(ENGINE_PATH)/src
LOCAL_EXPORT_C_INCLUDES:= $(ENGINE_PATH)/src
LOCAL_CFLAGS 	+= -DGX_OS_ANDROID -Wno-multichar 
LOCAL_CPPFLAGS	+= -DGX_OS_ANDROID -fno-rtti
LOCAL_EXPORT_CFLAGS := $(LOCAL_CFLAGS)
LOCAL_EXPORT_CPPFLAGS := $(LOCAL_CPPFLAGS)
LOCAL_WHOLE_STATIC_LIBRARIES := GXAndroid 
LOCAL_STATIC_LIBRARIES	:= gx_zlib gx_libpng gx_libjpeg
#LOCAL_LDLIBS 	:=
LOCAL_EXPORT_LDLIBS := -lEGL -lGLESv2 -llog -landroid -lOpenSLES
#__LOCAL_SRC_FILES_START__
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GAction.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GAppBundle.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GApplication.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GArray.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GAutoreleasePool.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GBaseContext.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GBuffer.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GBundle.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GCanvas.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GClass.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GCoder.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GColor.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GCondition.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GContext.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GD3DContext.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDShader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GData.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataArray.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataBuffer.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataList.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataReader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataString.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDataWriter.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GDib.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GError.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GFileBundle.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GFileManager.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GFileReader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GFileWriter.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GFrameBuffer.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GJpeg.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GList.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GLog.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GMShader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GMTLContext.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GMap.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GMatrix.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GMutex.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GNotice.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GNoticeCenter.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GNumber.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GOGLContext.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GOShader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GOWHash.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GObject.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GPieceData.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GPng.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GPtr.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GRBReader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GReader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GRunLoop.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GSRGraphics.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GSRTexture2D.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GSerialize.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GShader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GString.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GSystem.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GTString.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GTexture.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GTexture2D.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GThread.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GUUID.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GVector.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GWString.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GWindow.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GWriter.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXCWnd.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXCoder.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXData.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXDirectX.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXMath.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXMetal.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXOpenGL.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GXPthread.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GZipBundle.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GZipReader.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/GZipWriter.cpp
LOCAL_SRC_FILES += $(ENGINE_PATH_FROM_SRC)/src/glew.c
#__LOCAL_SRC_FILES_END__

include $(BUILD_STATIC_LIBRARY)

$(call import-module,external/zlib/lib/ard)
$(call import-module,external/libpng/lib/ard)
$(call import-module,external/libjpeg/lib/ard)


