/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gxengine_game_GAndroidActivity */

#ifndef _Included_com_gxengine_game_GAndroidActivity
#define _Included_com_gxengine_game_GAndroidActivity
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gxengine_game_GAndroidActivity_BIND_ABOVE_CLIENT
#define com_gxengine_game_GAndroidActivity_BIND_ABOVE_CLIENT 8L
#undef com_gxengine_game_GAndroidActivity_BIND_ADJUST_WITH_ACTIVITY
#define com_gxengine_game_GAndroidActivity_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_gxengine_game_GAndroidActivity_BIND_ALLOW_OOM_MANAGEMENT
#define com_gxengine_game_GAndroidActivity_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_gxengine_game_GAndroidActivity_BIND_AUTO_CREATE
#define com_gxengine_game_GAndroidActivity_BIND_AUTO_CREATE 1L
#undef com_gxengine_game_GAndroidActivity_BIND_DEBUG_UNBIND
#define com_gxengine_game_GAndroidActivity_BIND_DEBUG_UNBIND 2L
#undef com_gxengine_game_GAndroidActivity_BIND_EXTERNAL_SERVICE
#define com_gxengine_game_GAndroidActivity_BIND_EXTERNAL_SERVICE -2147483648L
#undef com_gxengine_game_GAndroidActivity_BIND_IMPORTANT
#define com_gxengine_game_GAndroidActivity_BIND_IMPORTANT 64L
#undef com_gxengine_game_GAndroidActivity_BIND_NOT_FOREGROUND
#define com_gxengine_game_GAndroidActivity_BIND_NOT_FOREGROUND 4L
#undef com_gxengine_game_GAndroidActivity_BIND_WAIVE_PRIORITY
#define com_gxengine_game_GAndroidActivity_BIND_WAIVE_PRIORITY 32L
#undef com_gxengine_game_GAndroidActivity_CONTEXT_IGNORE_SECURITY
#define com_gxengine_game_GAndroidActivity_CONTEXT_IGNORE_SECURITY 2L
#undef com_gxengine_game_GAndroidActivity_CONTEXT_INCLUDE_CODE
#define com_gxengine_game_GAndroidActivity_CONTEXT_INCLUDE_CODE 1L
#undef com_gxengine_game_GAndroidActivity_CONTEXT_RESTRICTED
#define com_gxengine_game_GAndroidActivity_CONTEXT_RESTRICTED 4L
#undef com_gxengine_game_GAndroidActivity_MODE_APPEND
#define com_gxengine_game_GAndroidActivity_MODE_APPEND 32768L
#undef com_gxengine_game_GAndroidActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_gxengine_game_GAndroidActivity_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_gxengine_game_GAndroidActivity_MODE_MULTI_PROCESS
#define com_gxengine_game_GAndroidActivity_MODE_MULTI_PROCESS 4L
#undef com_gxengine_game_GAndroidActivity_MODE_NO_LOCALIZED_COLLATORS
#define com_gxengine_game_GAndroidActivity_MODE_NO_LOCALIZED_COLLATORS 16L
#undef com_gxengine_game_GAndroidActivity_MODE_PRIVATE
#define com_gxengine_game_GAndroidActivity_MODE_PRIVATE 0L
#undef com_gxengine_game_GAndroidActivity_MODE_WORLD_READABLE
#define com_gxengine_game_GAndroidActivity_MODE_WORLD_READABLE 1L
#undef com_gxengine_game_GAndroidActivity_MODE_WORLD_WRITEABLE
#define com_gxengine_game_GAndroidActivity_MODE_WORLD_WRITEABLE 2L
#undef com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_DIALER
#define com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_DIALER 1L
#undef com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_DISABLE
#define com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_DISABLE 0L
#undef com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SEARCH_GLOBAL
#define com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SEARCH_GLOBAL 4L
#undef com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SEARCH_LOCAL
#define com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SEARCH_LOCAL 3L
#undef com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SHORTCUT
#define com_gxengine_game_GAndroidActivity_DEFAULT_KEYS_SHORTCUT 2L
#undef com_gxengine_game_GAndroidActivity_RESULT_CANCELED
#define com_gxengine_game_GAndroidActivity_RESULT_CANCELED 0L
#undef com_gxengine_game_GAndroidActivity_RESULT_FIRST_USER
#define com_gxengine_game_GAndroidActivity_RESULT_FIRST_USER 1L
#undef com_gxengine_game_GAndroidActivity_RESULT_OK
#define com_gxengine_game_GAndroidActivity_RESULT_OK -1L
/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnRestart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnRestart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnStart
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnStart
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnResume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnResume
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnPause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnPause
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnStop
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnWindowCreated
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnWindowCreated
  (JNIEnv *, jobject, jlong, jobject, jobject, jstring);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnWindowChanged
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;II)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnWindowChanged
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jint);

/*
 * Class:     com_gxengine_game_GAndroidActivity
 * Method:    jniOnWindowDestroyed
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidActivity_jniOnWindowDestroyed
  (JNIEnv *, jobject, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
