/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gxengine_game_GAndroidDaydream */

#ifndef _Included_com_gxengine_game_GAndroidDaydream
#define _Included_com_gxengine_game_GAndroidDaydream
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gxengine_game_GAndroidDaydream_BIND_ABOVE_CLIENT
#define com_gxengine_game_GAndroidDaydream_BIND_ABOVE_CLIENT 8L
#undef com_gxengine_game_GAndroidDaydream_BIND_ADJUST_WITH_ACTIVITY
#define com_gxengine_game_GAndroidDaydream_BIND_ADJUST_WITH_ACTIVITY 128L
#undef com_gxengine_game_GAndroidDaydream_BIND_ALLOW_OOM_MANAGEMENT
#define com_gxengine_game_GAndroidDaydream_BIND_ALLOW_OOM_MANAGEMENT 16L
#undef com_gxengine_game_GAndroidDaydream_BIND_AUTO_CREATE
#define com_gxengine_game_GAndroidDaydream_BIND_AUTO_CREATE 1L
#undef com_gxengine_game_GAndroidDaydream_BIND_DEBUG_UNBIND
#define com_gxengine_game_GAndroidDaydream_BIND_DEBUG_UNBIND 2L
#undef com_gxengine_game_GAndroidDaydream_BIND_EXTERNAL_SERVICE
#define com_gxengine_game_GAndroidDaydream_BIND_EXTERNAL_SERVICE -2147483648L
#undef com_gxengine_game_GAndroidDaydream_BIND_IMPORTANT
#define com_gxengine_game_GAndroidDaydream_BIND_IMPORTANT 64L
#undef com_gxengine_game_GAndroidDaydream_BIND_NOT_FOREGROUND
#define com_gxengine_game_GAndroidDaydream_BIND_NOT_FOREGROUND 4L
#undef com_gxengine_game_GAndroidDaydream_BIND_WAIVE_PRIORITY
#define com_gxengine_game_GAndroidDaydream_BIND_WAIVE_PRIORITY 32L
#undef com_gxengine_game_GAndroidDaydream_CONTEXT_IGNORE_SECURITY
#define com_gxengine_game_GAndroidDaydream_CONTEXT_IGNORE_SECURITY 2L
#undef com_gxengine_game_GAndroidDaydream_CONTEXT_INCLUDE_CODE
#define com_gxengine_game_GAndroidDaydream_CONTEXT_INCLUDE_CODE 1L
#undef com_gxengine_game_GAndroidDaydream_CONTEXT_RESTRICTED
#define com_gxengine_game_GAndroidDaydream_CONTEXT_RESTRICTED 4L
#undef com_gxengine_game_GAndroidDaydream_MODE_APPEND
#define com_gxengine_game_GAndroidDaydream_MODE_APPEND 32768L
#undef com_gxengine_game_GAndroidDaydream_MODE_ENABLE_WRITE_AHEAD_LOGGING
#define com_gxengine_game_GAndroidDaydream_MODE_ENABLE_WRITE_AHEAD_LOGGING 8L
#undef com_gxengine_game_GAndroidDaydream_MODE_MULTI_PROCESS
#define com_gxengine_game_GAndroidDaydream_MODE_MULTI_PROCESS 4L
#undef com_gxengine_game_GAndroidDaydream_MODE_NO_LOCALIZED_COLLATORS
#define com_gxengine_game_GAndroidDaydream_MODE_NO_LOCALIZED_COLLATORS 16L
#undef com_gxengine_game_GAndroidDaydream_MODE_PRIVATE
#define com_gxengine_game_GAndroidDaydream_MODE_PRIVATE 0L
#undef com_gxengine_game_GAndroidDaydream_MODE_WORLD_READABLE
#define com_gxengine_game_GAndroidDaydream_MODE_WORLD_READABLE 1L
#undef com_gxengine_game_GAndroidDaydream_MODE_WORLD_WRITEABLE
#define com_gxengine_game_GAndroidDaydream_MODE_WORLD_WRITEABLE 2L
#undef com_gxengine_game_GAndroidDaydream_START_CONTINUATION_MASK
#define com_gxengine_game_GAndroidDaydream_START_CONTINUATION_MASK 15L
#undef com_gxengine_game_GAndroidDaydream_START_FLAG_REDELIVERY
#define com_gxengine_game_GAndroidDaydream_START_FLAG_REDELIVERY 1L
#undef com_gxengine_game_GAndroidDaydream_START_FLAG_RETRY
#define com_gxengine_game_GAndroidDaydream_START_FLAG_RETRY 2L
#undef com_gxengine_game_GAndroidDaydream_START_NOT_STICKY
#define com_gxengine_game_GAndroidDaydream_START_NOT_STICKY 2L
#undef com_gxengine_game_GAndroidDaydream_START_REDELIVER_INTENT
#define com_gxengine_game_GAndroidDaydream_START_REDELIVER_INTENT 3L
#undef com_gxengine_game_GAndroidDaydream_START_STICKY
#define com_gxengine_game_GAndroidDaydream_START_STICKY 1L
#undef com_gxengine_game_GAndroidDaydream_START_STICKY_COMPATIBILITY
#define com_gxengine_game_GAndroidDaydream_START_STICKY_COMPATIBILITY 0L
#undef com_gxengine_game_GAndroidDaydream_STOP_FOREGROUND_DETACH
#define com_gxengine_game_GAndroidDaydream_STOP_FOREGROUND_DETACH 2L
#undef com_gxengine_game_GAndroidDaydream_STOP_FOREGROUND_REMOVE
#define com_gxengine_game_GAndroidDaydream_STOP_FOREGROUND_REMOVE 1L
/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnCreate
  (JNIEnv *, jobject);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnAttachedToWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnAttachedToWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnDreamingStarted
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnDreamingStarted
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnDreamingStopped
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnDreamingStopped
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnDetachedFromWindow
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnDetachedFromWindow
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnDestroy
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnDestroy
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnWindowCreated
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnWindowCreated
  (JNIEnv *, jobject, jlong, jobject, jobject, jstring);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnWindowChanged
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;II)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnWindowChanged
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jint);

/*
 * Class:     com_gxengine_game_GAndroidDaydream
 * Method:    jniOnWindowDestroyed
 * Signature: (JLcom/gxengine/game/GAndroidWindow;Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_game_GAndroidDaydream_jniOnWindowDestroyed
  (JNIEnv *, jobject, jlong, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
