//
//  GXGObjectUD.h
//  GX
//
//  Created by Gengxin Gu on 16/6/23.
//  Copyright © 2016年 Gengxin Gu. All rights reserved.
//

#ifdef GX_GOBJECT
#undef GX_GOBJECT_DECLARE_BASE
#undef GX_GOBJECT_DECLARE
#undef GX_PRIVATE_GOBJECT_DECLARE
#undef GX_VIRTUAL_GOBJECT_DECLARE
#undef GX_GOBJECT
#undef GX_FINAL_GOBJECT
#undef GX_PRIVATE_GOBJECT
#undef GX_VIRTUAL_GOBJECT
#undef GX_GOBJECT_IMPLEMENT_SUGGEST_GNT
#undef GX_GOBJECT_TEMPLATE_IMPLEMENT_SUGGEST_GNT
#undef GX_GOBJECT_IMPLEMENT
#undef GX_GOBJECT_TEMPLATE_IMPLEMENT
#endif
