/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gxengine_gx_GJavaJAPI */

#ifndef _Included_com_gxengine_gx_GJavaJAPI
#define _Included_com_gxengine_gx_GJavaJAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appCreate
 * Signature: (ILjava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appCreate
  (JNIEnv *, jclass, jint, jobject);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appStart
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appStart
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appResume
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appResume
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appIdle
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appIdle
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appPause
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appPause
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appStop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appStop
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appDestroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appDestroy
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    appLowMemory
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_appLowMemory
  (JNIEnv *, jclass);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    mainWindowHasCreated
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_mainWindowHasCreated
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    mainWindowHasChanged
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_mainWindowHasChanged
  (JNIEnv *, jclass, jobject, jint, jint);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    mainWindowHasDestroyed
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_mainWindowHasDestroyed
  (JNIEnv *, jclass, jobject);

/*
 * Class:     com_gxengine_gx_GJavaJAPI
 * Method:    mainWindowOnTouchEvent
 * Signature: (IIFF)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_gx_GJavaJAPI_mainWindowOnTouchEvent
  (JNIEnv *, jclass, jint, jint, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
