/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gxengine_GX */

#ifndef _Included_com_gxengine_GX
#define _Included_com_gxengine_GX
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_gxengine_GX
 * Method:    main
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_gxengine_GX_main
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
