/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_gxengine_GX */

#ifndef _Included_com_gxengine_GX
#define _Included_com_gxengine_GX
#ifdef __cplusplus
extern "C" {
#endif
#undef com_gxengine_GX_LaunchTypeActivity
#define com_gxengine_GX_LaunchTypeActivity 0L
#undef com_gxengine_GX_LaunchTypeDaydream
#define com_gxengine_GX_LaunchTypeDaydream 1L
/*
 * Class:     com_gxengine_GX
 * Method:    main
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_gxengine_GX_main
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
